apiVersion: v1
kind: Pod
metadata:
  name: web-pode
  labels:
    type: web-app
spec:
  containers:
  - name: web-server-apache
    image: httpd
    resources: 
      requests:
        cpu: "500m"
        memory: "128Mi"
      limits:
        cpu: "1000m"
        memory: "256Mi"