apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
data:
  #connetction data base
  database: mongodp
  database_uri: mongodp://localhost:27017
---

apiVersion: v1
kind: Pod
metadata:
  name: my-config-map-env
spec:
  containers:
  - name: my-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    envFrom:
     - configMapRef:
        name: my-cm
    command:
    - "bin/sh"
    - "-c"
    - "echo My Database = $database - $database_uri"
  restartPolicy: Never

