apiVersion: v1
kind: Pod
metadata:
  name: specific-node-pod

spec:
  containers:
  - name: redis
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  nodeSelector: 
    disktype: "ssd"