apiVersion: v1
kind: Pod
metadata:
  name: pod-apache
spec:
  containers:
  - name: my-apache
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
---

apiVersion: v1
kind: Pod
metadata:
  name: pod-nignx
spec:
  containers:
  - name: my-nignx
    image: nignx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"