apiVersion: v1
kind: Pod
metadata:
  name: podsecret-vol
spec:
  containers:
  - name: my-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    envFrom:
     - secretRef:
        name: my-secret
        optional: true
    volumeMounts:
    - name: my-vol
      mountPath: "/etc/my-vol"
      readOnly: true
  volumes:
  - name: my-vol
    secret:
      secretName: my-secret
      optional: true
